### PR TITLE
Upgrade dependencies and the PHP version

### PR DESCRIPTION
**Pull request by bkrukowski**

### CODE REVIEW

**Comment by colinodell** [comment]
Any chance this could be merged? I'd love to use this on PHP 8.1 but need the confidence of passing tests before including this in an important application.

**Comment by bkrukowski** [comment]
@colinodell thx for reminding. Tests have been fixed. I'll self review this pull request one more time a bit later, if all will be good, I'll merge it.

**Comment by bkrukowski** [comment]
@colinodell https://github.com/php-defer/php-defer/releases/tag/v5.0.4

**Comment by colinodell** [comment]
Awesome, thank you so much!

**Pull request merged**
